### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by oleksii03** [oleksii03/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by dasha-korotkykh** [comment]
Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самому, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
P.S. те саме стосується і інших issue

**Comment by oleksii03** [comment]
> Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самому, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
> P.S. те саме стосується і інших issue

Привіт! Я вже зрозумів. Так, знаю, але вибрав собі іншу людину. Дякую.

**Comment by oleksii03** [comment]
LANGUAGES
:uk: ENGLISH :fr: РУССКИЙ

SKILLS
PLAY FOOTBALL TENNIS SINGING COOKING

CHARACTER
AMBITIOUS NOT GREED INTERESTING Y CALM COMPETITIVE SOCIABLE CONFIDENT

LIKES smiley
FOOTBALL PIZZA WIFE PLAYSTATION FRUITS JUICE DOGS

DISLIKES disappointed
ALCOHOL  SMOKING PROUD PEOPLE CATS PORK RAIN

WANTS 🥺
CHAMPIONS LEAGUE CUP WORLD CUP GROW CHILDREN HAPPY RETIREMENT
